# Generated by Django 4.2 on 2023-11-22 18:00

from django.db import migrations, models
import webchat.models


class Migration(migrations.Migration):
    dependencies = [
        ("webchat", "0002_rename_conversation_message_conversation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("-timestamp",)},
        ),
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to=webchat.models.meesage_file_upload_path
            ),
        ),
    ]
